LRUDAO, FixedSizeDAO, LoggerService
foam-framework/foam2 pull request #1136
Opened 2018-04-12 18:25 UTC by xuerongCode

implement LRUDAO,
implement FixedSizedDAO
add Logger service
ticket: https://github.com/nanoPayinc/NANOPAY/issues/1388

2018-04-12 21:25 UTC, xuerongCode commented
@jlhughes @kgrgreer Please review

2018-04-13 11:44 UTC, jlhughes approved these changes

2018-04-13 13:48 UTC, adamvy commented on src/files.js
> +  { name: 'foam/nanos/logger/Log', flags: ['web']},
nanos files should be added to src/foam/nanos/nanos.js

2018-04-13 14:20 UTC, adamvy requested changes

2018-04-13 14:20 UTC, adamvy commented on src/foam/dao/FixedSizeDAO.java
> +    //TODO
What is the TODO here? At first glace this looks implemented, leave a more detailed comment if there's work to be done.

2018-04-13 14:20 UTC, adamvy commented on src/foam/dao/FixedSizeDAO.java
> +public class FixedSizeDAO
I wonder if its possible to implement this as a decorator, one which just tracks the number of puts and removes going through it and throws an error if you exceed the maxSize number of puts.

Then we can use any suitable underlying storage DAO such as JDAO or MDAO or even ClientDAO rather than having to implemented another ArrayDAO here.

2018-04-13 14:20 UTC, adamvy commented on src/foam/nanos/logger/GUIDLogger.java
> +  private FObject generateLogModel(String type, Object... args) {
I may be confused but what makes this a GUIDLogger?  Where is a GUID coming in to play?

2018-04-13 14:20 UTC, adamvy commented on src/foam/nanos/logger/GUIDLogger.js
> +      name: 'self',
I'm not sure this is doing what you think its doing, and it doesn't appear to be used anywhere, delete it?

2018-04-13 14:20 UTC, adamvy commented on src/foam/nanos/logger/GUIDLogger.js
> +foam.CLASS({
If we have both a Java and JS implementation, what about generating the Java one from the model rather than writing it by hand?

2018-04-13 14:20 UTC, adamvy commented on src/foam/nanos/logger/GUIDLogger.js
> +      if (arguments.length > 1) {
These method bodies look all the same except for the first parameter to addToDAO, make a helper method and call that rather than copying the code 5 times.

2018-04-13 14:20 UTC, adamvy commented on src/foam/nanos/logger/Log.js
> +        return '' + new Date().getTime() + '-' + Math.floor(Math.random() * 100000);;
You can add javaFactory too with the java equivalent code for this, then you don't have to put this logic in GUIDLogger.java but can keep it right beside the JS factory.  This makes it more readable as we can see the behaviour on all platforms side by side.

2018-04-13 14:20 UTC, adamvy commented on src/foam/nanos/logger/GUIDLogger.java
> +    log.setBelong(System.getProperty("user.name"));
Do we really want to log user.name?  That's the operating system level user that nanos is running as.  I guess it could be useful, but I would have expected instead to log the user for whom we're completing this DAO request.

2018-04-13 14:20 UTC, adamvy commented on src/foam/nanos/logger/Log.js
> +      name: 'belong',
I find belong a confusing name, maybe just call this user?  Also add a documentation: '' field describing what we're going to store here.

2018-04-13 14:20 UTC, adamvy commented on src/foam/dao/LRUDAO.java
> +public class LRUDAO
You seem to have implemented LRU and ConcurrentLRU as java level collections, and then implemented LRUDAO as a DAO on top of these collection classes.

What if instead we implemented LRUDAO as a DAO Decorator, then we can apply it to any underlying DAO storage mechanism like an MDAO, and get high performance queries for free.

2018-04-13 14:20 UTC, adamvy commented on src/foam/util/List.java
> +public class List<O> {
Yeah I think this would be better done at the DAO level so we can Decorate DAOs with a max size rather than Lists.

DAOs are more useful than Lists.

2018-04-13 14:47 UTC, kgrgreer commented on src/foam/nanos/logger/GUIDLogger.java
> +    log.setBelong(System.getProperty("user.name"));
FOAM already inserts a prefix logger which logs the current user when there is one.

2018-04-13 14:48 UTC, kgrgreer commented on src/foam/nanos/logger/GUIDLogger.java
> +public class GUIDLogger
I think DAOLogger would be a better name.

2018-04-13 18:14 UTC, kgrgreer commented on src/foam/dao/FixedSizeDAO.java
> +  private List<FObject> list;
Make instance variables be protected instead of private and end names with underscores. ie. rename list to list_.

2018-04-13 18:15 UTC, kgrgreer commented on src/foam/dao/FixedSizeDAO.java
> +    Iterator<FObject> i = list.iterator();
Easier to use Java's built-in iterator looping support:
for ( FObject i : list ) {

}

2018-04-13 18:16 UTC, kgrgreer commented on src/foam/dao/FixedSizeDAO.java
> +    while( i.hasNext() ) {
Add space between while and (. See FOAM coding style guide:
https://github.com/foam-framework/foam2/blob/master/doc/guides/StyleGuide.md

2018-04-13 18:18 UTC, kgrgreer commented on src/foam/nanos/logger/GUIDLogger.js
> +      return (!! e.name) ? '' + e.name : undefined;
Why is the !! needed?
Why is the '' + needed?
Is this just the same as 'e.name'?

2018-04-13 18:19 UTC, kgrgreer commented on src/foam/nanos/logger/Log.js
> +        return '' + new Date().getTime() + '-' + Math.floor(Math.random() * 100000);;
Add documentation to explain what you're doing and why.

2018-04-13 18:20 UTC, kgrgreer commented on src/foam/util/ConcurrentLRU.java
> +  private final ReentrantReadWriteLock rwl = new ReentrantReadWriteLock();
Here and elsewhere, make private vars protected and add underscore suffix.

2018-04-13 18:22 UTC, kgrgreer commented on src/foam/nanos/logger/Log.js
> +        return '' + new Date().getTime() + '-' + Math.floor(Math.random() * 100000);;
Why is this a random number rather than just a sequence number?

2018-04-13 19:00 UTC, kgrgreer commented
I think this whole thing could be greatly simplified and optimized but just having a CircularLogBuffer which uses a fixed size circular buffer to store new log entries. It also adapts this internal buffer into a partial-DAO. This DAO would only need to implement select() and maybe find().

2018-04-13 19:49 UTC, closed without merging