FixedSizeDAO
foam-framework/foam2 pull request #1297
Opened 2018-07-09 23:29 UTC by deejes

merge FixedSizeDAO to store a specified number of objects

2018-07-09 23:46 UTC, jlhughes requested changes

2018-07-09 23:46 UTC, jlhughes commented on src/foam/dao/FixedSizeDAO.js
> +getFixedSizeArray().add(obj);
put via the delegate first and place the result in the array.

2018-07-09 23:46 UTC, jlhughes commented on src/foam/dao/FixedSizeDAO.js
> +if ( sink.equals(null) ) {
This will fail if sink is null. 
Change to .   sink == null

2018-07-09 23:46 UTC, jlhughes commented on src/foam/dao/FixedSizeDAO.js
> +      javaFactory: `return new org.apache.commons.collections.buffer.CircularFifoBuffer(10000); `
move the buffer size to a property, then we can set it via the builder. 
also, on buffer size change, recreate the fixedSizeArray, then we can change it at runtime via a script.

2018-07-10 02:22 UTC, kgrgreer commented on src/foam/dao/FixedSizeDAO.js
> + * Copyright 2018 Google Inc. All Rights Reserved.
Not copyright Google.

/**
 * @license
 * Copyright 2018 The FOAM Authors. All Rights Reserved.
 * http://www.apache.org/licenses/LICENSE-2.0
 */

2018-07-10 04:27 UTC, deejes commented on src/foam/dao/FixedSizeDAO.js
> +      javaFactory: `return new org.apache.commons.collections.buffer.CircularFifoBuffer(10000); `
Do you know of an example for the second issue ( rerun factory on property update? ).
Also, will we be wanting to copy over however many preexisting logs will fit into the newly created array?

2018-07-10 11:36 UTC, jlhughes requested changes

2018-07-10 11:36 UTC, jlhughes commented on src/foam/dao/FixedSizeDAO.js
> +      javaFactory: `return new org.apache.commons.collections.buffer.CircularFifoBuffer(getFixedArraySize()); `
This buffer is itself not thread safe. 
Two options: 
1. Buffer fifo = BufferUtils.synchronizedBuffer(new CircularFifoBuffer());
2. Use a regular Array and add a synchronized 'nextIndex' method. 

Option 1 is easier as the CircularFifoBuffer handles correct iteration order during toArray on select().

2018-07-10 15:43 UTC, jlhughes approved these changes

2018-07-10 15:43 UTC, merged

2018-07-10 19:13 UTC, kgrgreer commented on src/foam/dao/FixedSizeDAO.js
> +  documentation: function () {/*
Just use a String rather than a function comment or a multi-line string (quoted with back-quotes "`") if it spans more than one line.

2018-07-10 19:13 UTC, kgrgreer commented on src/foam/dao/FixedSizeDAO.js
> +    'org.apache.commons.collections.buffer.CircularFifoBuffer',
sort imports

2018-07-10 19:14 UTC, kgrgreer commented on src/foam/dao/FixedSizeDAO.js
> +Object[] tester = getFixedSizeArray().toArray();
Is there a way to walk the data without making a copy?

2018-07-11 13:25 UTC, jlhughes commented on src/foam/dao/FixedSizeDAO.js
> +Object[] tester = getFixedSizeArray().toArray();
@kgrgreer Alternative is to use/manage an Array ourselves and not use the Apache CircularFifoBuffer.