Added modelled exception on DIG
foam-framework/foam2 pull request #1388
Opened 2018-07-27 20:58 UTC by minsunny

https://github.com/nanoPayinc/NANOPAY/issues/2688

Created error models, to deal with every DIG error case with an internal code starting from 1000.
It is shown with error code, type, message etc. as required format.

2018-07-27 21:55 UTC, jlhughes requested changes

2018-07-27 21:55 UTC, jlhughes commented on src/foam/nanos/dig/DigWebAgent.java
> +                                      .setMessage("DAO can not found: " + daoName)
replace with:  DAO not found:

2018-07-27 21:55 UTC, jlhughes commented on src/foam/nanos/dig/DigWebAgent.java
> +            //TODO: return exception
remove.

2018-07-27 21:55 UTC, jlhughes commented on src/foam/nanos/dig/DigWebAgent.java
> +                                            .setMessage("Invalid Json Format")
replace with: Invalid JSON Format

2018-07-27 21:55 UTC, jlhughes commented on src/foam/nanos/dig/DigWebAgent.java
> +                                        .setMessage("This" + format + "is not supported.")
replace with: Unsupported Format:   and provide the format string if possible.

2018-07-27 21:55 UTC, jlhughes commented on src/foam/nanos/dig/DigWebAgent.java
> +            .setMessage("Unsupported DAO")
Provide the dao name if possible.

2018-07-27 21:55 UTC, jlhughes commented on src/foam/nanos/dig/exception/DaoNoFoundException.js
> +  name: 'DaoNoFoundException',
Rename to DAONotFoundException

2018-07-27 21:55 UTC, jlhughes commented on src/foam/nanos/dig/exception/DaoNoFoundException.js
> +      value: 'NoFound'
Replace with: NotFound

2018-07-27 21:55 UTC, jlhughes commented on src/foam/nanos/dig/exception/DaoPutException.js
> +  name: 'DaoPutException',
Rename to DAOPutException

2018-07-29 01:16 UTC, kgrgreer commented on src/foam/lib/csv/CSVSupport.java
> +          throw new RuntimeException("CSV head format error");
What is a CSV head format error?

2018-07-29 01:17 UTC, kgrgreer commented on src/foam/nanos/dig/DigWebAgent.java
> +    PrintWriter   out            = x.get(PrintWriter.class);
Make line-up with other lines.

2018-07-30 13:39 UTC, merged