Update PasswordView with customized password visibility icon
foam-framework/foam2 pull request #1562
Opened 2018-09-18 13:51 UTC by Henry0422

To enable the passwordIcon feature when initialize password property:
```
{
   class: 'Password',
   name: 'password',
   view: { class: 'foam.u2.view.PasswordView', passwordIcon: true }
}
```

2018-09-19 15:53 UTC, Henry0422 commented
@kgrgreer I am not sure how to get the relative path of an icon in foam2.

After I add an icon file under `foam2/src/foam/u2` & put `{"class":"foam.nanos.servlet.ServletMapping","className":"foam.nanos.servlet.ImageServlet","pathSpec":"/images/*",initParameters:{"paths":"foam2/src/foam/u2/images"}}` at the end of the `http` in the  foam2 services file, the web page still cannot load the image based on the relative path (`/images/baseline-visibility_off-24px.svg`)

2018-09-25 23:18 UTC, kgrgreer commented on src/foam/nanos/auth/resetPassword/ResetView.js
> +          .start(this.CONFIRM_PASSWORD).end()
You can just do .add(this.CONFIRM_PASSWORD), which is shorter than start() and end().

2018-09-25 23:19 UTC, kgrgreer commented on src/foam/u2/view/PasswordView.js
> +    .input-field-container {
These are global names. Try not to pollute the global namespace, so use ^ and myClass() instead.

2018-09-25 23:19 UTC, kgrgreer commented on src/foam/u2/view/PasswordView.js
> +      defaultValue: false
defaultValue is from FOAM1, use value: instead. However, false is already the default so not needed.

2018-09-26 01:05 UTC, kgrgreer commented on src/foam/nanos/auth/SignInView.js
> +          .start(this.PASSWORD).end()
Here you can also just use .add() instead of start().end().

2018-09-26 01:07 UTC, kgrgreer commented on src/foam/u2/view/PasswordView.js
> +      this.inputElement.attrSlot(
You don't need to do this. the start('input') is mapped to a foam.u2.tag.Input element which already supports this logic. Just set it's onKey property and then bind to its data$.

2018-09-27 18:53 UTC, TW80000 requested changes

2018-09-27 18:53 UTC, TW80000 commented on src/foam/u2/view/PasswordView.js
> -  properties: [ [ 'type', 'password' ] ]
We still need this for the `type` attribute on the HTML input element to be set correctly.

```JavaScript
{
  class: 'String',
  name: 'type',
  value: 'password'
}
```

2018-09-28 19:38 UTC, TW80000 approved these changes

2018-09-28 19:41 UTC, merged