Distinguish between http and https
foam-framework/foam2 pull request #1589
Opened 2018-10-03 20:18 UTC by ZacZhang

Distinguish between http and https based on the default URL of AppConfig

2018-10-03 21:03 UTC, ronin00 requested changes
This change assumes as default a scenario where the incoming req URL protocol identifier doesn't match what should be used on URLs in the outbound resp.  (e.g: A loadbalancer strips the HTTPS and forwards the HTTP req to the webserver.  But the webserver should make sure to write it's hrefs as HTTPS in the response).

The problem is that the above scenario is not the DEFAULT for most webapps.  The simple default scenario would be where the HTTPS or HTTP terminate directly on the webserver.  And thus the protocol identifier of the req will simply match the protocol identifiers in outbound resp. 

Thus the default logic in the framework should account for the default scenario -- which was handled by the removed code.  

And any special logic for unusual handling:
- should be optional logic impl in the framework but controlled by a deployment time flag
- or be directly impl by the downstream user app via overrides/refinements mechanisms

2018-10-04 15:57 UTC, ronin00 approved these changes

2018-10-04 15:59 UTC, jlhughes approved these changes

2018-10-04 15:59 UTC, jlhughes commented on src/foam/nanos/app/AppConfig.js
> +      name: 'enableForceHttps',
rename to forceHttps
But this can wait for the next PR, we need to get this out

2018-10-04 15:59 UTC, jlhughes commented on src/foam/nanos/auth/Group.js
> +        if ( ! SafetyUtil.isEmpty(req.getRequestURI()) && ! SafetyUtil.isEmpty(config.getUrl())) {
Want to review this later.

2018-10-04 15:59 UTC, merged