Logout user/agent when being disabled
foam-framework/foam2 pull request #1760
Opened 2018-12-20 22:33 UTC by lchanmann

Forcefully logout user when being disabled:

- [x] Logout the user session
- [x] Logout all agents who currently login and act as the user

Extracted from: https://github.com/nanoPayinc/NANOPAY/pull/5354

2018-12-20 23:29 UTC, jlhughes requested changes

2018-12-20 23:29 UTC, jlhughes commented on src/foam/nanos/auth/LogoutDisabledUserDAO.js
> +    'net.nanopay.model.Business',
Please remove nanopay references

2018-12-20 23:29 UTC, jlhughes commented on src/foam/nanos/auth/LogoutDisabledUserDAO.js
> +
This nanopay business logic will have to be added on a nanopay side decorator.

2018-12-21 11:59 UTC, lchanmann commented on src/foam/nanos/auth/LogoutDisabledUserDAO.js
> +    'net.nanopay.model.Business',
Fixed

2018-12-21 11:59 UTC, lchanmann commented on src/foam/nanos/auth/LogoutDisabledUserDAO.js
> +
Fixed

2018-12-21 12:02 UTC, lchanmann commented
Comments addressed. Please take another look, thanks @jlhughes

2018-12-21 14:00 UTC, jlhughes approved these changes

2018-12-21 14:00 UTC, merged