Table Sorting Icon
foam-framework/foam2 pull request #1805
Opened 2019-01-18 20:37 UTC by blakegreen32

Added correct table sorting icon according to zeplin mocks, icon only displays if column has a label. Also took out close button from modal header as all modals now have an outer close button.

2019-01-18 20:43 UTC, kennyqiyenkan submitted a review, later dismissed

2019-01-18 20:43 UTC, kennyqiyenkan commented on src/foam/u2/view/UnstyledTableView.js
> +                console.log(column.label);
console.log

2019-01-18 21:33 UTC, Henry0422 requested changes

2019-01-18 21:33 UTC, Henry0422 commented on src/foam/u2/ModalHeader.js
> -      .start(this.CLOSE_MODAL).addClass('close').end();
It is not a good idea remove this `Close` button, it will affect all the app which is using the `ModalHeader.js`

2019-01-18 21:33 UTC, Henry0422 requested changes
Please double check the code in ModalHeader.js before merge..

2019-01-21 16:29 UTC, TW80000 requested changes
According to the design, there should be an 8px margin between the column heading and the icon. Please add that in. Something like

```CSS
^ th > img {
  margin-left: 8px;
}
```

should work. I noticed that we're also currently adding a space after the label. That leads to too much space between the label and the icon, so the space should be removed in favour of the 8px left-margin on this icon.

2019-01-22 17:23 UTC, TW80000 approved these changes
Tested and it LGTM, thanks!

2019-01-22 18:12 UTC, Henry0422 commented
I tested this PR as well. Looks good.

2019-01-22 18:19 UTC, Henry0422 requested changes
Sorry, one more thing. Can I ask if we can customize the generate the CSV file using `csvDriver`?
Right now, I got some information messed up in the generated CSV file. 
It might only happen to me?

2019-01-22 18:45 UTC, merged