Add DeletedAware interface and support
foam-framework/foam2 pull request #1809
Opened 2019-01-18 21:47 UTC by lchanmann

Address: https://github.com/nanoPayinc/NANOPAY/issues/5600

2019-01-18 21:51 UTC, jlhughes requested changes

2019-01-18 21:51 UTC, jlhughes commented on src/foam/nanos/auth/DeletedAwareDAO.js
> +        if ( obj instanceof DeletedAware ) {
Suspect you'll need to clone here.

2019-01-19 02:02 UTC, lchanmann commented on src/foam/nanos/auth/DeletedAwareDAO.js
> +        if ( obj instanceof DeletedAware ) {
Fixed

2019-01-19 02:05 UTC, lchanmann commented
@jlhughes please review again.

2019-01-20 03:44 UTC, jlhughes commented
Can you create a test case for this please. Thanks.

2019-01-22 14:47 UTC, jlhughes approved these changes

2019-01-22 14:47 UTC, merged