WIP (CPF-130) Monitor and Alarming
foam-framework/foam2 pull request #2082
Opened 2019-04-28 23:34 UTC by jlhughes

Initial Monitor and Alarm models.
Plus updates to configure via EasyDAO.

2019-04-29 15:46 UTC, lchanmann requested changes

2019-04-29 15:46 UTC, lchanmann commented on src/foam/dao/EasyDAO.js
> +      }
factory doesn't generate Java code.

2019-04-29 15:46 UTC, lchanmann commented on src/foam/dao/EasyDAO.js
>        generateJava: false
we need Java code generation.

2019-04-29 15:46 UTC, lchanmann commented on src/foam/nanos/monitor/test/TestMonitor.js
> +      ((foam.dao.DAO) getX().get("monitorDAO")).put(monitor);
No need to `put(monitor)` RulerDAO will take care of it.

2019-06-02 02:55 UTC, jlhughes commented
Really messed up after experimenting with cleaning up files.

2019-06-02 02:55 UTC, closed without merging