CPF-277 #comment changed to validate input fields from user model
foam-framework/foam2 pull request #2097
Opened 2019-05-02 19:53 UTC by noodlemoodle

2019-05-03 20:25 UTC, Nauna commented
tested with corresponding PR: https://github.com/nanoPayinc/NANOPAY/pull/6692

and all works wonderfully 🥇

2019-05-07 02:00 UTC, jlhughes requested changes

2019-05-07 02:00 UTC, jlhughes commented on src/foam/nanos/auth/User.js
> +          return 'Last Name Field Required.'
```suggestion
          return 'Last Name Required.'
```

2019-05-07 02:00 UTC, jlhughes commented on src/foam/nanos/auth/User.js
> +          return 'Company Name Field Required.';
```suggestion
          return 'Company Name Required.';
```

2019-05-07 02:00 UTC, jlhughes commented on src/foam/nanos/auth/User.js
> +          return 'Email Field Required.';
```suggestion
          return 'Email Required.';
```

2019-05-07 15:24 UTC, merged