Cpf 2438/remove authenticated dao
foam-framework/foam2 pull request #2443
Opened 2019-07-25 20:06 UTC by noodlemoodle

2019-07-25 21:05 UTC, smirnovaka requested changes
can you please go over properties like `lazy`, `serve` `authenticate` ... and check if their default values are appropriate. If so, do not repeat them

2019-07-25 21:05 UTC, smirnovaka commented on src/services
> +p({"class":"foam.nanos.boot.NSpec","name":"localGroupPermissionJunctionDAO","description":"The junction DAO for the many-to-many relationship between groups and permissions","serve":false,"serviceScr
isn't `authorize` true by default?

2019-07-25 21:05 UTC, smirnovaka commented on src/services
> +p({"class":"foam.nanos.boot.NSpec","name":"userCapabilityJunctionDAO","lazy":false,"serve":true,"authenticate":false,"serviceScript":"dao = new foam.dao.EasyDAO.Builder(x).setAuthorize(false).setJour
can you please remove `authenticate:false`, almost none of the services should be `authenticate:false` except the ones that let you signup/login

2019-07-25 21:05 UTC, penzital commented on src/services
> +p({"class":"foam.nanos.boot.NSpec","name":"userCapabilityJunctionDAO","lazy":false,"serve":true,"authenticate":false,"serviceScript":"dao = new foam.dao.EasyDAO.Builder(x).setAuthorize(false).setJour
remove `lazy:false`

2019-08-22 16:56 UTC, TW80000 reviewed
I think it would still be valuable to have a test suite for the `StandardAuthorizer`, much like the current `AuthenticatedDAOTest`.

2019-08-27 00:23 UTC, closed without merging