untransianted required properties
foam-framework/foam2 pull request #2550
Opened 2019-08-27 16:07 UTC by michaelconnor468

2019-08-27 16:09 UTC, TW80000 requested changes

2019-08-27 16:09 UTC, TW80000 commented on src/foam/nanos/session/Session.js
> +      transient: true
Sorry, this should just be `storageTransient`, not `networkTransient` as well. If it were `networkTransient` then admins wouldn't be able to see how many uses sessions have.

2019-08-27 16:18 UTC, TW80000 approved these changes

2019-08-28 03:59 UTC, jlhughes reviewed
I would expect lastUsed to also required storageTransient.  
See discussion in https://github.com/foam-framework/foam2/pull/2542

2019-08-28 16:07 UTC, jlhughes requested changes
Make lastUsed storageTransient. 
On restart the session will effectively be reset.  We'll err with this rather than write every session update for now.

2019-08-28 21:45 UTC, jlhughes approved these changes

2019-08-29 03:17 UTC, jlhughes commented on src/foam/nanos/session/Session.js
>        name: 'uses'
```suggestion
      name: 'uses',
```

2019-08-29 13:56 UTC, merged