removed select support
foam-framework/foam2 pull request #2582
Opened 2019-09-09 15:17 UTC by michaelconnor468

2019-09-09 15:32 UTC, KateMengjunXia requested changes
Why not just remove the whole overriding 'select_' method?

2019-09-10 00:59 UTC, kgrgreer commented
Do we still use the HidePropertiesSink anywhere? Can we remove it now?

2019-09-10 14:33 UTC, michaelconnor468 commented
I don’t think so

2019-09-10 14:33 UTC, michaelconnor468 commented
- Kate

2019-09-10 16:13 UTC, merged