MultiPartID index support
foam-framework/foam2 pull request #285
Opened 2017-04-10 19:48 UTC by jacksonic

Fixes #135.

Some tests became more efficient as they gained a default index on the test model's Int property.

2017-05-03 19:17 UTC, mdittmer requested changes
Just nits & request for comments/explanation.

2017-05-03 19:17 UTC, mdittmer commented on src/foam/dao/index/MultiKeyIndex.js
> +      for (var i = 1; (i < key.length && subIndex); ++i) {
Moar spacings.

2017-05-03 19:17 UTC, mdittmer commented on src/foam/dao/index/MultiKeyIndex.js
> +      for (var i = ps.length - 1; i >= 0; --i) {
ditto.

2017-05-03 19:17 UTC, mdittmer commented on test/src/lib/Index.js
> +      var plan = idxInstance
Can we get comments in the `beforeEach` and/or in the tests explaining why we expect certain `length`s and `size()`s? It's hard to review test changes like this without much context on what's being setup and why we expect what we expect.

2017-05-05 13:50 UTC, jacksonic commented on test/src/lib/Index.js
> +      var plan = idxInstance
Added details about what the test is doing

2017-05-05 13:51 UTC, jacksonic commented
Comments addressed, PTAL for anyone else interested

2017-05-15 17:33 UTC, mdittmer approved these changes
This LGTM

2018-02-15 14:03 UTC, closed without merging