Clustering
foam-framework/foam2 pull request #2858
Opened 2019-12-04 03:33 UTC by jlhughes

2019-12-05 20:50 UTC, lchanmann requested changes

2019-12-05 20:50 UTC, lchanmann commented on src/foam/nanos/ruler/RulerDAO.js
> +    });
ruleDAO.listen needs to be between the initial ruleDAO and ruleDAO.where at line 121.

https://github.com/foam-framework/foam2/pull/2166/commits/04f531c28d3437260556c9e22927d56338ebbcb6

2019-12-05 20:50 UTC, lchanmann commented on src/foam/nanos/ruler/RulerDAO.js
> +      javaCode: `addRule(dao, predicate, getRulesList());`
looks like addRuleList is not being used.

2020-05-12 03:15 UTC, jlhughes commented
Closed - replaced by CPF-157/Medusa

2020-05-12 03:15 UTC, closed without merging