Enum Support - Java Code Generation
foam-framework/foam2 pull request #322
Opened 2017-05-08 14:19 UTC by TanayParikh

- Added Enum code generation support for Java
- Updated src/foam/java/Enum.js starter file
- Added refinements in src/foam/java/refinements.js

Note: 
There seems to be a fair bit of code repetition in the `refinements.js` file for `foam.core.enum`, `foam.core.AbstractEnum`, `foam.core.EnumModel`. Is there any way to clean this up into a single refinement?

2017-05-08 15:07 UTC, kgrgreer commented
@adamvy Can you please review. Thanks

2017-05-08 15:09 UTC, adamvy commented
@kgrgreer Only if you review #318 :)

2017-05-08 15:31 UTC, adamvy requested changes

2017-05-08 15:31 UTC, adamvy commented on src/foam/java/Enum.js
>    private final int index_;
Do we really need index_ and ordinal_ ?  Ordinal should be sufficient.

2017-05-08 15:31 UTC, adamvy commented on src/foam/java/Enum.js
> +// Defines template for the EnumModel
Overall I wonder if we can do some better code sharing by making a foam.java.Enum class, and having it extend foam.java.Class

An Enum is in essence a Class with a fixed number of implementations.  If we extend foam.java.Class and update the outputJava method to output the VALUES, as well as whatever tweaks we need to match java enum syntax, we should also get methods/fields for free.


I would start by defining foam.java.Enum as a foam.CLASS() that extends foam.java.Class, and then trying to get the output correct.  Then refine buildJavaClass() onto foam.core.EnumModel, which should build a foam.java.Enum.

2017-05-08 16:07 UTC, TanayParikh commented on src/foam/java/Enum.js
>    private final int index_;
Thanks, that's a good point. I've removed the index property.

2017-05-08 17:56 UTC, kgrgreer commented on src/foam/java/Enum.js
>    if (this.androidResource) {
Do we need this now? When we do, can we integrate it with FOAM's Message axiom support and then integrate the message support with Android Resources.

2017-05-08 18:12 UTC, TanayParikh commented on src/foam/java/Enum.js
>    if (this.androidResource) {
The androidResource is directly from the FOAM 1 enum template. Should I just go ahead and remove it?

2017-05-08 18:20 UTC, kgrgreer commented on src/foam/java/Enum.js
>    if (this.androidResource) {
Yes, just remove for now.

2017-05-08 18:29 UTC, TanayParikh commented on src/foam/java/Enum.js
>    if (this.androidResource) {
Removed

2017-05-09 15:21 UTC, TanayParikh commented on src/foam/java/Enum.js
> +// Defines template for the EnumModel
Hi Adam,

I've made foam.java.Enum and extended it from foam.java.Class. I've also updated the general code generation logic to move away from templates and more along the lines of the FOAM2 structure.

2017-05-09 16:02 UTC, adamvy commented on src/foam/java/Enum.js
> +  name: 'EnumModel',
This can just be called Enum, same way foam.java.Class is call Class not ClassModel.

2017-05-09 16:03 UTC, adamvy commented on src/foam/java/Enum.js
> +    ['javaType', 'java.lang.Enum'],
Are these used anywhere?  I'm pretty sure these properties should be refined on foam.core.Enum

2017-05-09 16:04 UTC, adamvy commented on src/foam/java/Enum.js
> +    function toJavaSource() {
This should be inherited from foam.java.Class

2017-05-09 16:05 UTC, adamvy commented on src/foam/java/Enum.js
> +    ['javaType', 'java.lang.Enum'],
Ah reading further, you did refine them onto foam.core.Enum, which is good, these properties here should probably be deleted.

2017-05-09 16:05 UTC, adamvy commented on src/foam/java/refinements.js
> +  properties: [
I don't believe these properties are needed here.

2017-05-09 16:06 UTC, adamvy commented on src/foam/java/refinements.js
> +  properties: [
Again with these properties :), I don't think you need them here either

2017-05-09 16:07 UTC, adamvy commented on src/foam/java/Enum.js
> +    function outputJava(o) {
This is a good start.

Next I would look at if you can refactor this to share some code with outputJava in foam.java.Class.  There is a fair amount of duplication here that can probably be cleaned up.

2017-05-10 14:33 UTC, eatonk commented
@adamvy Are there any more changes required for this PR?

2017-05-10 15:31 UTC, adamvy commented
Sorry for the delay, this looks good to me, thanks!

2017-05-10 15:31 UTC, merged