add loop over exception
foam-framework/foam2 pull request #3504
Opened 2020-05-26 18:47 UTC by hchoura

@lchanmann Please can you review.

2020-05-26 19:13 UTC, jlhughes requested changes

2020-05-26 19:13 UTC, jlhughes commented on src/foam/core/CompoundException.java
> +      for ( int i = 0 ; i < exceptions_.size() ; i++ ) {
@hchoura no.
Do this output when AppConfig.MODE is TEST.
after this block 
'throw this' as before.

2020-05-26 19:13 UTC, jlhughes commented on src/foam/core/CompoundException.java
> +        throw (RuntimeException) exceptions_.get(i);
this makes no sense.

2020-05-26 19:57 UTC, lchanmann commented on src/foam/core/CompoundException.java
> -      throw this;
`throw this;` makes more sense than looping the exception list then throws the first one.

2020-06-02 22:33 UTC, jlhughes commented
superseded by another PR

2020-06-02 22:33 UTC, closed without merging