Add Owner Setting Rule Actions for DIG/SUGAR
foam-framework/foam2 pull request #3686
Opened 2020-07-10 14:45 UTC by nick-prat

This will allow them to be SPID aware, I haven't included the changes to the services/rules journals to actually enforce them though.  Currently have the journal changes in an integration journal deployment only, will submit a PR in the future with them.

2020-07-10 15:48 UTC, jlhughes reviewed
See inline comment regarding using createdBy and CreatedByAgent. 
what is the purpose of the 'owner' property?

2020-07-10 15:48 UTC, jlhughes commented on src/foam/nanos/dig/DIGOwnerRuleAction.js
> +/**
Is this needed, can we not use 'createdBy' as that has both createdBy and createdByAgent.

2020-07-13 14:53 UTC, jlhughes commented on src/services
> +    .setCreatedByAware(true)
This is not necessary.

2020-07-13 14:53 UTC, jlhughes commented on src/foam/nanos/dig/DIG.js
> +    'foam.nanos.auth.CreatedByAware'
Didn't realize we didn't have createdBy, created, lastModified, ... 
Please add the other three.

2020-07-14 17:31 UTC, nanoscott requested changes

2020-07-14 17:31 UTC, nanoscott commented on src/foam/nanos/dig/DIG.js
> +      storageOptional: true,
created* properties shouldn't be storageOptional, only lastModified* properties.

2020-07-14 19:32 UTC, jlhughes approved these changes

2020-07-14 20:40 UTC, nanoscott approved these changes

2020-07-14 21:48 UTC, merged