Implementing attribute parsing in HTMLLexer
foam-framework/foam2 pull request #383
Opened 2017-05-23 20:16 UTC by m-cheung

Purposed solution to #325

2017-05-23 20:46 UTC, mdittmer reviewed
Some initial thoughts. Still need to check semantic actions and think about tests when I'm not reviewing from a phone.

2017-05-23 20:46 UTC, mdittmer commented on src/foam/parsers/HTMLLexer.js
> +      name: 'element'
Element sounds confusing wrt html elements. Maybe "name" or "key"?

2017-05-23 20:46 UTC, mdittmer commented on src/foam/parsers/HTMLLexer.js
> +      class: 'Array',
We  want class: 'FObjectArray', of: '(fully qualified attribute class name)'

2017-05-23 20:46 UTC, mdittmer commented on src/foam/parsers/HTMLLexer.js
> +  name: 'Attribute',
This and Tag should probably either be called HTML(Classname) or move to foam.parsers.html

2017-05-23 21:27 UTC, m-cheung commented on src/foam/parsers/HTMLLexer.js
> +  name: 'Attribute',
I have placed `Attributes`, `Embed` and `Tag` under `foam.parsers.html` in the next change

2017-05-24 12:40 UTC, mdittmer commented
We should add tests that address [issues identified here](https://stackoverflow.com/questions/4015345/how-to-properly-escape-quotes-inside-html-attributes). In particular:

- Single or double quotes
- Converting `&name;`-style escapes

2017-05-24 13:44 UTC, mdittmer requested changes
Finished reviewing all code. Mostly just need a few more tests.

2017-05-24 13:44 UTC, mdittmer commented on src/foam/parsers/HTMLLexer.js
> +          attributes: function(v) { return v; },
No need for this line; `v => v` is the default action.

2017-05-24 13:44 UTC, mdittmer commented on src/foam/parsers/HTMLLexer.js
> +            return Attribute.create({ name: v[0], value: v[1] });
Will `v[1]` be `undefined` or `null`? We should probably set `Attribute.value` to `null`.

2017-05-24 13:44 UTC, mdittmer commented on src/foam/parsers/HTMLLexer.js
> +          value: function(v) { return v; }
Ditto: Don't need default action.

2017-05-24 13:44 UTC, mdittmer commented on test/src/parsers/HTMLLexer.js
> +      expect(value.attributes.length > 2).toBe(true);
Let's use `toBeGreaterThan` here.

2017-05-24 13:44 UTC, mdittmer commented on test/src/parsers/HTMLLexer.js
> +  it('should parse tags multiple attributes', function() {
I think we should have more tests, each that tests one thing (or a particular combination of things). Maybe something like:

- Multiple attributes
- Attribute without value
- Attribute without quotes
- Attribute in single quotes
- Attribute with `&name;` escape of some kind
- Attribute containing whitespace (maybe include ` \t\r\n`)

2017-05-24 20:48 UTC, m-cheung commented
All requested changes have been made and should be good to go now

2017-05-24 20:52 UTC, m-cheung commented on src/foam/parsers/HTMLLexer.js
> +              plus(alt(sym('escape'), notChars('\'" \t\r\n<>'))),
I was required to alter this case as well, since Chrome parses `<option value=&amp;Potato />`

2017-05-25 17:31 UTC, m-cheung commented on src/foam/parsers/HTMLLexer.js
>              });
I noticed that `Embed` and `maybeEmbed` did not previously have a type. However, I noticed that the way the grammar is defined, these nodes act like self closing items (i.e., there is only one node for each set of opening and closing tags for these types. Thus, they essentially act as `OPEN_CLOSE`).

Although this change can be discarded, it does make my work a lot easier when performing tag matching.

2017-06-05 21:53 UTC, m-cheung commented on test/src/parsers/HTMLLexer.js
> +      expect(value[1]).toBe('sc < ri ? p > t : en');
I believe this should be the expected result now? I need confirmation on this

2017-06-06 13:29 UTC, mdittmer commented
I believe this PR is being made obsolete by a simpler "true lexer" that @m-cheung is working on.

2017-06-06 13:29 UTC, closed without merging