remove the message in bottom
foam-framework/foam2 pull request #4101
Opened 2020-10-19 21:46 UTC by RachaelDing

https://nanopay.atlassian.net/browse/NP-2286

2020-10-19 22:12 UTC, jlhughes requested changes
@lchanmann @RachaelDing  Rachael where is this being called/setup from?  That is where this should be set to false.

2020-10-20 15:57 UTC, RachaelDing commented
@jlhughes 
This is only called in the initE() method of the same class. And nowhere setup it after initialization, so I changed the initial value of if. Should I set it in iniE() method instead? Thank you.

2020-10-20 16:05 UTC, lchanmann commented
@RachaelDing there are two places that call it and is bound to this.isValid$
<img width="1464" alt="Screen Shot 2020-10-20 at 12 02 47 PM" src="https://user-images.githubusercontent.com/441658/96612845-45496b80-12cc-11eb-9a3f-cc662a34359d.png">

2020-10-20 16:09 UTC, RachaelDing commented
@lchanmann  I changed 'showValidNumberOfChoicesHelper', not 'isValidNumberOfChoices'

2020-10-20 19:23 UTC, jlhughes commented on src/foam/nanos/crunch/ui/CapableMinMaxCapabilityWizardlet.js
> +        showValidNumberOfChoicesHelper: false,
remove this please.

2020-10-20 19:30 UTC, RachaelDing commented on src/foam/nanos/crunch/ui/CapableMinMaxCapabilityWizardlet.js
> +        showValidNumberOfChoicesHelper: false,
removed

2020-10-20 20:36 UTC, merged